version: '3.9'

services:
  react_app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true