name: Docker Test CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "Mongo is up" && break
            echo "Waiting for Mongo..."
            sleep 2
          done

      - name: Run tests inside API container
        run: docker-compose exec -T api npm test

      - name: Tear down
        if: always()
        run: docker-compose down